{{- $availableEnvironments := list "prepro" "prod" }}
{{- if has .Release.Namespace $availableEnvironments }}
---

kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- include "helm.annotations" . | nindent 4 }}
spec:
  hosts:
    {{- if eq "prod" .Release.Namespace }}
    - {{ .Values.istio.dnsPrefix }}.api.core.jobint.biz
    {{- else if eq "prepro" .Release.Namespace }}
    - {{ .Values.istio.dnsPrefix }}.prepro.api.core.jobint.biz
    {{- end }}
  gateways:
    - {{ template "application.fullname" . }}
  http:
    - headers:
        request:
          add:
            x-envoy-retry-on: 'gateway-error,connect-failure,refused-stream'
          set:
            x-envoy-max-retries: '10'
      route:
        - destination:
            host: {{ template "application.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local

{{- end -}}
