---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.fullname" . }}-secrets
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- include "helm.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.application.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
