---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.fullname" . }}-mp-token
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- include "helm.annotations" . | nindent 4 }}
type: Opaque
data:
  MP_TOKEN: {{ .Values.application.MP_TOKEN | b64enc }}
