apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    {{- include "application.labels" . | indent 4 }}
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- include "helm.annotations" . | nindent 4 }}
  {{- if .Values.service }}
  {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-80
      port: 80
      protocol: TCP
      targetPort: {{ .Values.application.port }}
  selector:
    {{- include "application.labels" . | indent 4 }}
